# Generated by Django 2.2.7 on 2021-06-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addtocart',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
